version: "3.8"
services:
  server: 
    container_name: server
    depends_on: 
      - db
    build: ./server
    ports: 
      - "5000:5000"
  db:
    container_name: db
    image: "postgres:alpine"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
  front:
    container_name: front
    build: ./website
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - server